Repository FrancoA56/FinalProjectServer, pull requests merged in 2023-10, with the labels that each got.

#48 Fix/preset get handlers
  src/db.ts
  src/handlers/preset/getPresetByIdHandler.ts
  src/handlers/preset/getPresetHandler.ts
  src/models/Invoice.ts
Labels: help wanted

#51 Feat/review endpoints
  package-lock.json
  src/controllers/review/addReviewController.ts
  src/controllers/review/getReviewController.ts
  src/handlers/review/addReviewHandler.ts
  src/handlers/review/getReviewHandler.ts
  src/models/Review.ts
  src/routes/index.ts
  src/routes/review.ts
Labels: enhancement, ready to merge

#58 Update/preset get endpoints
  package-lock.json
  src/controllers/preset/addPresetController.ts
  src/controllers/preset/editPresetController.ts
  src/controllers/preset/getPresetController.ts
  src/handlers/preset/addPresetHandler.ts
  src/handlers/preset/editPresetHandler.ts
  src/handlers/preset/getPresetHandler.ts
  src/models/Preset.ts
Labels: fix, enhancement

#60 feature(login0):added route,function and handler for auth0s users
  src/controllers/user/login0.ts
  src/handlers/user/login0Handler.ts
  src/routes/user.ts
Labels: ready to merge

#59 Feature(payment-paypal): The option to pay via PayPal has been added to controllers and handlers
  package-lock.json
  package.json
  src/controllers/shop/addOrderController.ts
  src/controllers/shop/order/addOrderController.ts
  src/controllers/shop/order/createPaymentOrderController.ts
  src/controllers/shop/order/getOrderByEmailController.ts
  src/controllers/shop/order/paypal/cancelPaymentOrderControler.ts
  src/controllers/shop/order/paypal/capturePaymentOrderController.ts
  src/handlers/preset/getPresetHandler.ts
  src/handlers/shop/invoice/addInvoiceHandler.ts
  src/handlers/shop/invoice/updateStatePaidInvoiceHandler.ts
  src/handlers/shop/order/paypal/TokenAuthentication.ts
  src/handlers/shop/order/paypal/capturePaymentOrderHandler.ts
  src/handlers/shop/order/paypal/createPaymentPaypalHandler.ts
  src/models/Invoice.ts
  src/routes/shop.ts
  src/utils/config.ts
Labels: ready to merge

#63 feat(getPreset): Added feature to query ids to search
  src/controllers/preset/getPresetController.ts
  src/handlers/preset/getPresetHandler.ts
Labels: ready to merge

#65 Fix(orders): The way orders are recorded and deleted has been optimized
  src/controllers/shop/order/addOrderController.ts
  src/controllers/shop/order/deleteOrderItemController.ts
  src/controllers/shop/order/getOrderByEmailController.ts
  src/handlers/shop/invoice/addInvoiceHandler.ts
  src/handlers/shop/order/addOrderHandler.ts
  src/handlers/shop/order/addOrderItemHandler.ts
  src/handlers/shop/order/checkOrderItemExistence.ts
  src/handlers/shop/order/deleteOrderHandler.ts
  src/handlers/shop/order/getOrderByEmailHandler.ts
  src/models/OrderItem.ts
  src/routes/shop.ts
Labels: ready to merge

#66 Feature(Email-BankTransfer): Email confirmation for purchase and new payment method
  package-lock.json
  package.json
  src/controllers/shop/order/createPaymentOrderController.ts
  src/controllers/shop/order/paypal/capturePaymentOrderController.ts
  src/controllers/shop/order/responseInfoBankTransfer.ts
  src/handlers/shop/errorHandler.ts
  src/handlers/shop/interfaceResponse.ts
  src/handlers/shop/invoice/UpdatePaymentStatusHandler.ts
  src/handlers/shop/invoice/addInvoiceHandler.ts
  src/handlers/shop/invoice/addInvoiceItemHandler.ts
  src/handlers/shop/invoice/getInvoiceByPaymentId.ts
  src/handlers/shop/invoice/updateStatePaidInvoiceHandler.ts
  src/handlers/shop/order/paypal/capturePaymentOrderHandler.ts
  src/handlers/shop/order/paypal/createPaymentPaypalHandler.ts
  src/handlers/shop/order/sendEmail/sendEmail.ts
  src/models/Invoice.ts
  src/templates/emailInfoBankTransfer.ts
  src/templates/emailResponsePurchase.ts
  src/templates/responsePaymentError.ts
  src/templates/responsePaymentSuccessFul.ts
  src/utils/config.ts
  src/utils/emailConfig.ts
Labels: ready to merge

#69 feat(presets): Added image and url to presets
  src/controllers/preset/addPresetController.ts
  src/controllers/preset/editPresetController.ts
  src/handlers/preset/addPresetHandler.ts
  src/handlers/preset/editPresetHandler.ts
  src/handlers/preset/getPresetByIdHandler.ts
  src/handlers/preset/getPresetHandler.ts
  src/models/Preset.ts
Labels: enhancement, ready to merge

#71 edited getPresetController added 2 lines for React/Admin configuration
  src/controllers/preset/getPresetController.ts
  src/server.ts
Labels: ready to merge

#70 feature(filter&order users)
  src/controllers/user/getUser.ts
  src/handlers/user/getUserHandler.ts
  src/handlers/user/registerHandler.ts
  src/routes/user.ts
Labels: ready to merge

#72 Preset changes (images and filters)
  src/controllers/preset/addPresetController.ts
  src/db.ts
  src/handlers/preset/addPresetHandler.ts
  src/handlers/preset/getPresetHandler.ts
  src/models/Preset.ts
  src/models/PresetImage.ts
Labels: ready to merge

#74 Fix/getuserhandler
  src/controllers/user/getUser.ts
  src/handlers/user/getUserHandler.ts
Labels: ready to merge

#73 fix forgot password Handle
  src/handlers/user/forgotPasswordHandler.ts
Labels: ready to merge

#75 fix forgot password Link
  src/handlers/user/forgotPasswordHandler.ts
Labels: ready to merge

#76 feature(user id): added column id and modified getUser return
  src/controllers/user/getUser.ts
  src/handlers/user/getUserHandler.ts
  src/models/User.ts
Labels: ready to merge

#78 Update/preset get endpoints
  src/controllers/preset/getPresetController.ts
  src/handlers/preset/getPresetByIdHandler.ts
  src/handlers/preset/getPresetHandler.ts
  src/models/Preset.ts
Labels: ready to merge

#80 fix/getUserHandler
  src/controllers/user/getUser.ts
  src/handlers/user/banUserHandler.ts
  src/handlers/user/forgotPasswordHandler.ts
  src/handlers/user/getUserHandler.ts
Labels: ready to merge

#85 fixed(forgot)
  src/handlers/user/forgotPasswordHandler.ts
Labels: ready to merge

#87 hardcoded url of forgot email
  src/handlers/user/forgotPasswordHandler.ts
Labels: ready to merge

#86 Feature(ChangePaymentStatus): Added the option to change the payment status
  src/controllers/shop/Invoice/getInvoiceByEmailController.ts
  src/controllers/shop/Invoice/getInvoiceByParamController.ts
  src/controllers/shop/Invoice/updatePaymentStatusController.ts
  src/controllers/shop/order/paypal/capturePaymentOrderController.ts
  src/handlers/shop/invoice/UpdatePaymentStatusHandler.ts
  src/handlers/shop/invoice/getInvoiceByIdHandler.ts
  src/routes/shop.ts
Labels: ready to merge

#88 Fix(changeStatusPayment): optimization
  src/controllers/shop/Invoice/getInvoiceByParamController.ts
  src/controllers/shop/Invoice/updatePaymentStatusController.ts
  src/controllers/shop/order/paypal/capturePaymentOrderController.ts
  src/handlers/shop/invoice/UpdatePaymentStatusHandler.ts
Labels: ready to merge
